on:
  workflow_dispatch:

jobs:
  add:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Add date
        run: date > date.txt
      - name: commmit and push
        run: |
              time-date="$(date +%H-%M-%S-%N)"
              git config user.name github-actions
              git config user.email github-actions@github.com
              git branch add-"${time-date}"
              git checkout "${time-date}"
              git add .
              git commit -m 'add'
              git push origin
