on:
  workflow_dispatch:

jobs:
  add:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Add date
        run: date +%H-%M-%S-%N > date.txt
      - name: commmit and push
        run: |
              git config user.name github-actions
              git config user.email github-actions@github.com
              git branch add-"$(cat date.txt)"
              git checkout add-"$(cat date.txt)"
              git add .
              git commit -m 'add'
              git push origin
